/* GiftGenius gift idea bank — 150+ curated ideas.
 * Fields: n=name, d=short description, i=interest keys, a=age bands, lo/hi=price range USD.
 * Works in browser (global GIFT_BANK) and Node (module.exports) for tests. */
const GIFT_BANK = [
// ---- Gaming (10)
{n:"Mechanical keyboard",d:"Tactile RGB mechanical keyboard for late-night sessions",i:["gaming","tech"],a:["teen","adult"],lo:60,hi:120},
{n:"Gaming headset",d:"Comfy 7.1 surround headset with noise-cancelling mic",i:["gaming"],a:["teen","adult"],lo:40,hi:100},
{n:"Wireless game controller",d:"Pro wireless controller with extra paddles",i:["gaming"],a:["teen","adult"],lo:50,hi:75},
{n:"Game store gift card",d:"Let them pick their own games — zero guesswork",i:["gaming"],a:["teen","adult"],lo:20,hi:60},
{n:"XL desk mat",d:"Stitched-edge desk mat that upgrades any battlestation",i:["gaming","tech"],a:["teen","adult"],lo:20,hi:35},
{n:"Retro handheld console",d:"Thousands of classics in a pocket console",i:["gaming"],a:["teen","adult"],lo:35,hi:60},
{n:"LED light strips",d:"Room-glow LED strips with music sync",i:["gaming","tech"],a:["teen","adult"],lo:25,hi:45},
{n:"Controller thumb grips",d:"Precision thumb grips, 6-pack",i:["gaming"],a:["teen","adult"],lo:10,hi:15},
{n:"Gaming mouse",d:"Lightweight precision gaming mouse",i:["gaming"],a:["teen","adult"],lo:30,hi:80},
{n:"Hoodie blanket",d:"Oversized wearable blanket for couch gaming",i:["gaming","selfcare"],a:["teen","adult"],lo:35,hi:55},
// ---- Tech (10)
{n:"Wireless earbuds",d:"Noise-cancelling true wireless earbuds",i:["tech","music"],a:["teen","adult"],lo:50,hi:150},
{n:"20K power bank",d:"Fast-charge brick that refuels a phone 4x",i:["tech","travel"],a:["teen","adult","senior"],lo:30,hi:50},
{n:"Waterproof Bluetooth speaker",d:"Rugged speaker for shower, beach, or backyard",i:["tech","music","outdoors"],a:["teen","adult"],lo:40,hi:90},
{n:"USB-C hub",d:"7-in-1 dock for laptop minimalists",i:["tech"],a:["adult"],lo:35,hi:60},
{n:"Portable SSD 1TB",d:"Pocket-sized blazing storage",i:["tech","photo"],a:["teen","adult"],lo:70,hi:110},
{n:"Smart bulbs 4-pack",d:"App-controlled color bulbs, voice compatible",i:["tech"],a:["teen","adult"],lo:40,hi:70},
{n:"Digital photo frame",d:"WiFi frame the whole family can send photos to",i:["tech","photo"],a:["adult","senior"],lo:80,hi:150},
{n:"E-reader",d:"Glare-free reader with weeks of battery",i:["tech","reading"],a:["teen","adult","senior"],lo:100,hi:140},
{n:"Phone tripod stand",d:"Sturdy tripod for video calls and vlogging",i:["tech","photo"],a:["teen","adult"],lo:20,hi:35},
{n:"Cable organizer kit",d:"Desk-tidy kit that ends cable spaghetti",i:["tech"],a:["adult"],lo:15,hi:25},
// ---- Cooking (9)
{n:"Chef's knife",d:"8-inch pro chef knife, razor sharp",i:["cooking"],a:["adult"],lo:40,hi:80},
{n:"Cast iron skillet",d:"Pre-seasoned skillet that lasts generations",i:["cooking"],a:["adult"],lo:30,hi:60},
{n:"Spice collection",d:"24-jar world spice collection",i:["cooking"],a:["adult","senior"],lo:35,hi:55},
{n:"Personalized apron",d:"Apron embroidered with their name",i:["cooking"],a:["adult"],lo:25,hi:40},
{n:"Cuisine cookbook",d:"100-recipe cookbook from a cuisine they love",i:["cooking","reading"],a:["adult"],lo:20,hi:35},
{n:"Infused olive oil trio",d:"Three small-batch infused olive oils",i:["cooking"],a:["adult","senior"],lo:30,hi:50},
{n:"Pour-over coffee kit",d:"Dripper, filters, and tasting notes",i:["cooking","coffee"],a:["adult"],lo:30,hi:55},
{n:"Bento lunch box",d:"Leakproof bento with compartments",i:["cooking"],a:["kid","teen","adult"],lo:20,hi:35},
{n:"Loose-leaf tea sampler",d:"12 rare loose-leaf teas in a gift box",i:["cooking","coffee"],a:["adult","senior"],lo:25,hi:40},
// ---- Garden (7)
{n:"Garden tool set",d:"9-piece tools with canvas tote",i:["garden"],a:["adult","senior"],lo:30,hi:55},
{n:"Herb seed kit",d:"12 culinary herb varieties to grow indoors",i:["garden","cooking"],a:["teen","adult","senior"],lo:20,hi:30},
{n:"Memory-foam kneeling pad",d:"Thick kneeling pad for long garden days",i:["garden"],a:["adult","senior"],lo:20,hi:30},
{n:"Brass plant mister",d:"Elegant brass mister for houseplants",i:["garden","plants"],a:["adult"],lo:15,hi:25},
{n:"Leather garden gloves",d:"Goatskin gloves that actually fit",i:["garden"],a:["adult","senior"],lo:20,hi:30},
{n:"Squirrel-proof bird feeder",d:"Feeder that outsmarts the squirrels",i:["garden"],a:["adult","senior"],lo:25,hi:45},
{n:"Cedar raised bed kit",d:"4x4 raised bed, assembles in an hour",i:["garden"],a:["adult"],lo:80,hi:130},
// ---- Fitness (8)
{n:"Resistance bands set",d:"5 stackable bands, 10–50 lbs",i:["fitness"],a:["teen","adult"],lo:25,hi:40},
{n:"Premium yoga mat",d:"6mm non-slip mat with alignment lines",i:["fitness","selfcare"],a:["teen","adult"],lo:30,hi:55},
{n:"Foam roller",d:"Deep-tissue roller for recovery days",i:["fitness"],a:["adult"],lo:25,hi:40},
{n:"Insulated steel bottle",d:"32oz bottle, 24h cold",i:["fitness","outdoors"],a:["teen","adult"],lo:25,hi:40},
{n:"Weighted jump rope",d:"Adjustable weighted rope",i:["fitness"],a:["teen","adult"],lo:20,hi:30},
{n:"Gym duffel",d:"Duffel with vented shoe compartment",i:["fitness","travel"],a:["teen","adult"],lo:40,hi:70},
{n:"Massage ball set",d:"3 firmness levels for knots",i:["fitness","selfcare"],a:["adult"],lo:15,hi:25},
{n:"Running belt",d:"Bounce-free belt for phone and gels",i:["fitness","sports"],a:["teen","adult"],lo:20,hi:30},
// ---- Reading (7)
{n:"Bestseller novel",d:"A hit novel in their favorite genre",i:["reading"],a:["teen","adult","senior"],lo:15,hi:28},
{n:"Clip-on reading light",d:"Warm dimmable book light",i:["reading"],a:["adult","senior"],lo:15,hi:25},
{n:"Lay-flat journal",d:"Linen hardcover journal",i:["reading","art"],a:["teen","adult"],lo:20,hi:35},
{n:"Canvas library tote",d:"Bookish quote tote, heavy canvas",i:["reading"],a:["teen","adult"],lo:15,hi:25},
{n:"Audiobook gift card",d:"3 months of audiobooks",i:["reading","tech"],a:["adult"],lo:30,hi:45},
{n:"Tree wooden bookends",d:"Hand-carved tree bookends",i:["reading"],a:["adult"],lo:25,hi:40},
{n:"Art print puzzle 1000pc",d:"Museum-art jigsaw, 1000 pieces",i:["reading","boardgames"],a:["teen","adult","senior"],lo:18,hi:30},
// ---- Music (7)
{n:"Vinyl record",d:"Their favorite album on vinyl",i:["music"],a:["teen","adult"],lo:25,hi:40},
{n:"Beginner ukulele kit",d:"Soprano uke with tuner and bag",i:["music"],a:["kid","teen","adult"],lo:50,hi:80},
{n:"Over-ear headphones",d:"Studio-sound over-ears",i:["music","tech"],a:["teen","adult"],lo:80,hi:150},
{n:"Guitar picks tin",d:"24 assorted picks in a tin",i:["music"],a:["teen","adult"],lo:12,hi:20},
{n:"Folding music stand",d:"Sturdy folding stand with bag",i:["music"],a:["teen","adult"],lo:30,hi:50},
{n:"Concert poster frame",d:"12x18 frame for gig posters",i:["music"],a:["teen","adult"],lo:20,hi:30},
{n:"Bluetooth karaoke mic",d:"Echo mic with speaker built in",i:["music"],a:["kid","teen"],lo:30,hi:50},
// ---- Art (7)
{n:"Sketchbook + pencil set",d:"A5 sketchbook with 12 graphite pencils",i:["art"],a:["teen","adult"],lo:20,hi:35},
{n:"Watercolor set 48",d:"48 vibrant pans with brushes",i:["art"],a:["kid","teen","adult"],lo:25,hi:45},
{n:"Paint-by-numbers kit",d:"Custom-photo paint-by-numbers option",i:["art"],a:["adult","senior"],lo:25,hi:40},
{n:"Air-dry clay kit",d:"Clay with sculpting tools",i:["art","crafts"],a:["kid","teen"],lo:20,hi:30},
{n:"Alcohol markers 40",d:"Dual-tip markers, 40 colors",i:["art"],a:["teen","adult"],lo:30,hi:50},
{n:"Tabletop easel",d:"Beechwood tabletop easel",i:["art"],a:["teen","adult"],lo:30,hi:50},
{n:"Framed art print",d:"Museum-quality framed print",i:["art"],a:["adult"],lo:30,hi:60},
// ---- Outdoors (8)
{n:"Camping hammock",d:"Hammock with tree straps included",i:["outdoors"],a:["teen","adult"],lo:40,hi:70},
{n:"Insulated cooler 20qt",d:"Keeps ice 5 days",i:["outdoors"],a:["adult"],lo:60,hi:100},
{n:"Binoculars 10x42",d:"Bright birding binoculars",i:["outdoors","travel"],a:["adult","senior"],lo:60,hi:120},
{n:"Rechargeable lantern",d:"1000-lumen camp lantern",i:["outdoors"],a:["teen","adult"],lo:30,hi:50},
{n:"Merino hiking socks 3pk",d:"Cushioned merino socks",i:["outdoors","fitness"],a:["adult"],lo:30,hi:45},
{n:"15-function multitool",d:"Pocket multitool for everything",i:["outdoors","crafts"],a:["teen","adult"],lo:40,hi:70},
{n:"500-lumen headlamp",d:"Rechargeable trail headlamp",i:["outdoors"],a:["teen","adult"],lo:25,hi:40},
{n:"Insulated thermos",d:"48h hot / 24h cold thermos",i:["outdoors","coffee"],a:["adult"],lo:30,hi:50},
// ---- Travel (6)
{n:"Packing cubes 6pc",d:"Compression cubes that end chaos",i:["travel"],a:["teen","adult"],lo:25,hi:40},
{n:"Memory-foam travel pillow",d:"Ergonomic neck pillow",i:["travel","selfcare"],a:["adult"],lo:30,hi:50},
{n:"Hanging toiletry bag",d:"Waterproof bag with hook",i:["travel"],a:["teen","adult"],lo:25,hi:45},
{n:"Universal travel adapter",d:"Works in 150+ countries, USB-C fast",i:["travel","tech"],a:["adult"],lo:25,hi:40},
{n:"Scratch-off world map",d:"Map to scratch visited countries",i:["travel"],a:["teen","adult"],lo:25,hi:40},
{n:"Leather luggage tags 2pk",d:"Full-grain leather tags",i:["travel"],a:["adult"],lo:15,hi:25},
// ---- Pets (6)
{n:"Pet toy bundle",d:"10 toys for endless play",i:["pets"],a:["adult"],lo:20,hi:30},
{n:"Custom pet portrait voucher",d:"Digital painting of their pet",i:["pets","art"],a:["adult"],lo:40,hi:80},
{n:"Ceramic treat jar",d:"Airtight treat jar",i:["pets"],a:["adult"],lo:25,hi:40},
{n:"Orthopedic pet bed",d:"Memory-foam bed for old joints",i:["pets"],a:["adult","senior"],lo:50,hi:90},
{n:"No-pull harness",d:"Padded no-pull walking harness",i:["pets","outdoors"],a:["adult"],lo:30,hi:50},
{n:"Pet bandana 3pk",d:"Stylish bandanas",i:["pets","fashion"],a:["adult"],lo:15,hi:25},
// ---- Photography (5)
{n:"Instant camera",d:"Prints photos on the spot",i:["photo"],a:["teen","adult"],lo:70,hi:100},
{n:"Phone lens kit",d:"Wide + macro clip-on lenses",i:["photo","tech"],a:["teen","adult"],lo:30,hi:50},
{n:"Mini photo printer",d:"Bluetooth pocket printer",i:["photo","tech"],a:["teen","adult"],lo:90,hi:130},
{n:"Travel tripod 60in",d:"Tall stable tripod",i:["photo"],a:["teen","adult"],lo:40,hi:70},
{n:"Woven camera strap",d:"Comfy artisan camera strap",i:["photo","fashion"],a:["adult"],lo:25,hi:40},
// ---- Movies (5)
{n:"Mini projector",d:"1080p backyard cinema projector",i:["movies","tech"],a:["teen","adult"],lo:80,hi:140},
{n:"Theater popcorn maker",d:"Old-school popcorn cart popper",i:["movies","cooking"],a:["kid","teen","adult"],lo:30,hi:50},
{n:"Movie night box",d:"Snacks, trivia cards, and glow",i:["movies"],a:["teen","adult"],lo:25,hi:40},
{n:"Streaming gift card",d:"3 months of their favorite service",i:["movies"],a:["teen","adult"],lo:25,hi:45},
{n:"Weighted throw blanket",d:"Cozy weighted throw for movie nights",i:["movies","selfcare"],a:["adult","senior"],lo:50,hi:90},
// ---- Crafts & DIY (7)
{n:"3D printing pen",d:"Draw in 3D, filament included",i:["crafts","tech"],a:["teen","adult"],lo:40,hi:70},
{n:"Candle making kit",d:"Soy wax, scents, and molds",i:["crafts","selfcare"],a:["teen","adult"],lo:30,hi:50},
{n:"39pc tool kit",d:"Home-repair starter kit",i:["crafts"],a:["adult"],lo:40,hi:70},
{n:"Embroidery starter kit",d:"Hoop, floss, and patterns",i:["crafts","art"],a:["teen","adult"],lo:20,hi:35},
{n:"Birdhouse woodworking kit",d:"Pre-cut cedar birdhouse kit",i:["crafts"],a:["kid","teen","adult"],lo:30,hi:50},
{n:"Deluxe sewing kit",d:"200pc sewing essentials",i:["crafts"],a:["adult"],lo:25,hi:40},
{n:"Soap making kit",d:"Shea soap with molds and scents",i:["crafts","selfcare"],a:["teen","adult"],lo:30,hi:45},
// ---- Board games (6)
{n:"Epic strategy board game",d:"90-minute strategy classic",i:["boardgames"],a:["teen","adult"],lo:40,hi:60},
{n:"Party game",d:"Hilarious 4–10 player party game",i:["boardgames"],a:["teen","adult"],lo:25,hi:40},
{n:"Escape room in a box",d:"At-home escape puzzle",i:["boardgames"],a:["teen","adult"],lo:25,hi:35},
{n:"Wooden chess set",d:"Classic Staunton chess set",i:["boardgames"],a:["kid","teen","adult","senior"],lo:30,hi:60},
{n:"Modern card game pack",d:"3 hit card games in one box",i:["boardgames"],a:["teen","adult"],lo:30,hi:45},
{n:"2000pc landscape puzzle",d:"Epic landscape jigsaw",i:["boardgames","reading"],a:["adult","senior"],lo:20,hi:30},
// ---- Self-care (7)
{n:"Bath bomb gift set",d:"12 fizzy bath bombs",i:["selfcare"],a:["teen","adult"],lo:25,hi:40},
{n:"Soy candle trio",d:"Three calming soy candles",i:["selfcare"],a:["teen","adult","senior"],lo:25,hi:40},
{n:"Silk sleep mask set",d:"Silk mask + earplugs",i:["selfcare","travel"],a:["adult"],lo:20,hi:30},
{n:"Essential oil diffuser",d:"Ultrasonic diffuser with oils",i:["selfcare"],a:["adult"],lo:30,hi:50},
{n:"Cozy sock set 5pk",d:"Fluffy socks, 5 pairs",i:["selfcare","fashion"],a:["teen","adult","senior"],lo:20,hi:30},
{n:"Gratitude journal",d:"5-minute daily gratitude journal",i:["selfcare","reading"],a:["teen","adult"],lo:18,hi:28},
{n:"Weighted eye pillow",d:"Lavender eye pillow",i:["selfcare"],a:["adult"],lo:20,hi:30},
// ---- Kids (8)
{n:"Building block set",d:"Age-matched creative building set",i:["kids"],a:["kid"],lo:30,hi:60},
{n:"Kids science kit",d:"50 hands-on experiments",i:["kids","science"],a:["kid"],lo:30,hi:50},
{n:"Oversized plush companion",d:"Giant huggable plush",i:["kids"],a:["kid"],lo:25,hi:40},
{n:"RC stunt car",d:"1:18 remote stunt car",i:["kids"],a:["kid","teen"],lo:30,hi:50},
{n:"Kids art easel",d:"Double-sided easel with supplies",i:["kids","art"],a:["kid"],lo:40,hi:70},
{n:"Storybook collection",d:"5 beloved storybooks boxed",i:["kids","reading"],a:["kid"],lo:25,hi:40},
{n:"Building blocks 250pc",d:"Classic 250-piece block tub",i:["kids"],a:["kid"],lo:30,hi:50},
{n:"Kids beginner telescope",d:"Easy-focus kids telescope",i:["kids","science"],a:["kid","teen"],lo:50,hi:80},
// ---- Fashion (5)
{n:"Wool scarf",d:"Soft merino wool scarf",i:["fashion"],a:["teen","adult","senior"],lo:30,hi:55},
{n:"RFID leather wallet",d:"Slim leather wallet, RFID safe",i:["fashion"],a:["adult"],lo:40,hi:70},
{n:"Polarized sunglasses",d:"Classic polarized shades",i:["fashion","travel"],a:["teen","adult"],lo:50,hi:90},
{n:"Premium canvas tote",d:"Heavy-duty everyday tote",i:["fashion"],a:["teen","adult"],lo:25,hi:40},
{n:"Minimalist watch",d:"Clean minimalist watch",i:["fashion"],a:["adult"],lo:60,hi:120},
// ---- Coffee & tea (5)
{n:"French press 34oz",d:"Classic 34oz French press",i:["coffee","cooking"],a:["adult"],lo:30,hi:50},
{n:"Pour-over dripper set",d:"Ceramic dripper + carafe",i:["coffee"],a:["adult"],lo:35,hi:55},
{n:"Barista mug set of 4",d:"12oz stoneware mugs",i:["coffee"],a:["adult"],lo:30,hi:45},
{n:"Matcha starter set",d:"Whisk, bowl, and ceremonial matcha",i:["coffee","selfcare"],a:["teen","adult"],lo:30,hi:50},
{n:"Gooseneck kettle",d:"Precision-pour kettle",i:["coffee"],a:["adult"],lo:40,hi:70},
// ---- Plants (5)
{n:"Monstera deliciosa",d:"6-inch potted monstera",i:["plants"],a:["teen","adult"],lo:30,hi:50},
{n:"Succulent set of 6",d:"Six easy succulents",i:["plants"],a:["teen","adult","senior"],lo:25,hi:40},
{n:"Ceramic pot set of 3",d:"Glazed pots with drainage",i:["plants"],a:["adult"],lo:30,hi:50},
{n:"Terrarium kit",d:"Glass terrarium with tools",i:["plants","crafts"],a:["teen","adult"],lo:35,hi:55},
{n:"Houseplant care book",d:"Care guide for 100 plants",i:["plants","reading"],a:["adult"],lo:20,hi:30},
// ---- Sports (5)
{n:"Indoor/outdoor basketball",d:"All-surface basketball",i:["sports"],a:["kid","teen","adult"],lo:25,hi:40},
{n:"Adjustable dumbbell pair",d:"Space-saving adjustable dumbbells",i:["sports","fitness"],a:["teen","adult"],lo:60,hi:100},
{n:"Soccer ball size 5",d:"Match-quality soccer ball",i:["sports"],a:["kid","teen"],lo:20,hi:30},
{n:"USB bike light set",d:"Bright rechargeable bike lights",i:["sports","tech"],a:["teen","adult"],lo:25,hi:40},
{n:"Golf balls 24pk",d:"24 distance golf balls",i:["sports"],a:["adult"],lo:30,hi:50},
// ---- Science (5)
{n:"70mm beginner telescope",d:"Stargazing telescope with tripod",i:["science"],a:["teen","adult"],lo:80,hi:130},
{n:"Chemistry set",d:"100 safe experiments",i:["science","kids"],a:["kid","teen"],lo:40,hi:70},
{n:"App-controlled robot kit",d:"Build and code a robot",i:["science","tech"],a:["kid","teen"],lo:50,hi:90},
{n:"Galaxy star projector",d:"Room-filling galaxy projector",i:["science","selfcare"],a:["kid","teen","adult"],lo:30,hi:50},
{n:"Pocket microscope 120x",d:"Pocket microscope for young scientists",i:["science"],a:["kid","teen"],lo:25,hi:40},
// ---- Wine (4)
{n:"Wine aerator",d:"Pour-through aerator for smoother wine",i:["wine","cooking"],a:["adult"],lo:20,hi:35},
{n:"Crystal wine glasses 4pk",d:"Four lead-free crystal glasses",i:["wine"],a:["adult"],lo:40,hi:70},
{n:"Wine tasting journal",d:"Log 100 wines with tasting notes",i:["wine","reading"],a:["adult"],lo:20,hi:30},
{n:"Bamboo wine rack",d:"12-bottle bamboo rack",i:["wine"],a:["adult"],lo:30,hi:50},
];
if (typeof module !== "undefined" && module.exports) module.exports = { GIFT_BANK };
